### ISSUE TITLE
lib\audio_stream\http_stream.c:456:9: error: implicit declaration of function 'esp_http_client_set_redirection' [-Werror=implicit-function-declaration]

### ISSUE THREAD

**Issue by junhuanchen** [maxgerhardt/pio-esp-adf-example#2]
![image](https://user-images.githubusercontent.com/32978053/56777553-c6719080-6804-11e9-9cb2-5282cb4e30dc.png)

see this

![image](https://user-images.githubusercontent.com/32978053/56777565-d5f0d980-6804-11e9-9de8-c1105e0aa740.png)

So pay attention to the username.

For example, I am juwan.

![image](https://user-images.githubusercontent.com/32978053/56777572-eacd6d00-6804-11e9-8b96-448336099d33.png)

**Comment by maxgerhardt** [comment]
Does it compile after changing this? As I have described in the [README](https://github.com/maxgerhardt/pio-esp-adf-example#building), this must per done per-user at the moment, unfortunately.

**Comment by junhuanchen** [comment]
Yes, I left a mark for posterity
